
  @swagger
  /api/v1/auth/register:
    post:
     summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
       201:
         description: User registered successfully
       400:
         description: Bad request
 

router.post("/register", register);
